### ISSUE TITLE
(SA-1) Super Mario RPG - Beetle Mania Score Showing Incorrectly

### ISSUE THREAD

**Issue by s3phir0th115** [RedGuyyyy/sd2snes#12]
[Super Mario RPG - Legend of the Seven Stars (USA) (srm Save).zip](https://github.com/RedGuyyyy/sd2snes/files/2264776/Super.Mario.RPG.-.Legend.of.the.Seven.Stars.USA.srm.Save.zip)

When playing the Beetle Mania mini game in Super Mario RPG, the score shows different characters instead of showing numbers consistently. This behavior does not appear with Higan.

My test system is a Super NT, not sure on the SD2SNES revision. The SA-1 core is the latest as of this time of writing, v03. The behavior does not occur on the Super NT with the original cartridge.

I've attached a copy of my srm file to help, since getting access to the game takes a significant amount of in game time. To load Beetle Mania you open the menu with X and select the Game option.

**Comment by James-F2** [comment]
Confirmed.

![20180807_175104](https://user-images.githubusercontent.com/31185814/43783587-c34ad3de-9a6a-11e8-8da2-2fc6265904b5.jpg)

**Comment by RedGuyyyy** [comment]
Fixed in v04.
