### ISSUE TITLE
USB2SNES firmware prevents Gradius 3 SA-1 hack from running on SD2SNES Pro

### ISSUE THREAD

**Issue by GerryHolt** [RedGuyyyy/sd2snes#16]
When attempted to play the Gradius 3 SA-1 mod, I discovered the while the usb2snes firmware was installed, the game would lock on boot (at the white grid screen), or would sometimes boot after a fresh power on, but have garbaged graphics on the ship and power up.

When I reverted back to stock 1.10.3 drivers, the game booted up with no issues.

I'm not sure if this info is helpful, but I'm running this on a shvc-cpu-01 Super Famicom using a stock power supply.

**Comment by RedGuyyyy** [comment]
Give v11 a try: https://github.com/RedGuyyyy/sd2snes/releases/tag/usb2snes_v11

A bug was introduced in v10 where special-chip games could crash due to missing some state that is only present in the non-special chip FPGA file.  The fix is to avoid writing it for special-chip games.

**Comment by GerryHolt** [comment]
Yup, boots up fine and no graphical issues at first glance. I'll give it a full play through tomorrow to make sure it's all good, but I doubt it'll have issues.
