### ISSUE TITLE
DSP Chip Issues

### ISSUE THREAD

**Issue by GerryHolt** [RedGuyyyy/sd2snes#17]
I'm not sure if this was an issue in the previous version, but it seems that DSP chips (eg. Mario Kart and Pilotwings) are broken in v11. Mario Kart won't go past the nintendo logo and Pilotwings won't load levels.

**Comment by RedGuyyyy** [comment]
This is a bug in the non-USB enabled firmware source code.  DSP doesn't get compiled in for some reason.  You can copy the attached file on top of v11 or re-download v11 to fix it.

[fpga_base.zip](https://github.com/RedGuyyyy/sd2snes/files/3359248/fpga_base.zip)

**Comment by GerryHolt** [comment]
Sorry, I'm not sure I understand, both games play fine on the official firmware on the pro model. Guess I don't need to though if it's fixed in this version. 

Thanks!

**Comment by RedGuyyyy** [comment]
The publicly available source has the bug for the mk3 (pro), but the author of the official firmware likely fixed it locally before releasing the official firmware.

`ifdef MK2 <- bug
`ifndef DEBUG
upd77c25 snes_dspx (

**Comment by GerryHolt** [comment]
Ahhh okay, that makes sense. Thanks for clarifying!
